<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { computed, ref, onMounted, onUnmounted } from 'vue';
import axios from 'axios';
const props=defineProps({purchase:Object,paymentError:String,returnHint:String});
const status=ref(props.purchase.status);
const paid=ref(props.purchase.status==='paid'),checking=ref(false),error=ref(props.paymentError||''),message=ref(''); const cancelForm=useForm({}); let timer,attempts=0;
const pesos=cents=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(cents/100);
const verify=async()=>{if(checking.value||paid.value)return;checking.value=true;error.value='';try{const {data}=await axios.post(route('credits.verify',props.purchase.id));paid.value=data.paid;status.value=data.status;message.value=data.paid?'Your minutes have been added.':'Payment is not confirmed yet. If you just paid, please wait a moment and check again.';}catch(e){error.value=e.response?.data?.message||'Could not check payment yet.';}finally{checking.value=false;}};
onMounted(()=>{if(props.purchase.status==='pending'){verify();timer=setInterval(()=>{if(paid.value||status.value!=='pending'||++attempts>=12){clearInterval(timer);return;}verify();},10000);}});
onUnmounted(()=>clearInterval(timer));
const stateCopy=computed(()=>({paid:['Minutes added','Your payment was verified and your minutes are available.'],pending:['Awaiting payment confirmation','If you already paid, check the status here before starting another purchase.'],creating:['Preparing your checkout','Your checkout is being prepared. Refresh shortly to see its status.'],setup_failed:['Checkout could not open','No minutes were added. Return to Minutes and try PayMongo checkout again.'],failed:['Payment failed','The provider did not confirm a successful payment. Return to Minutes to try again.'],cancelled:['Payment cancelled','The provider marked this checkout as cancelled. You can start a new purchase from Minutes.'],expired:['Checkout expired','This checkout is no longer available. Return to Minutes to start a new purchase.']}[paid.value?'paid':status.value]||['Payment status unavailable','Check again before starting another purchase.']));
</script>
<template><Head title="Minute purchase" /><AuthenticatedLayout><section class="mx-auto max-w-2xl px-5 py-12"><Link :href="route('credits')" class="text-sm text-accent-text underline">← Minutes</Link><div class="mt-7 rounded-3xl border border-border bg-surface p-6 shadow-sm sm:p-9"><span class="inline-flex h-12 w-12 items-center justify-center rounded-full bg-accent-soft text-2xl text-accent-text" aria-hidden="true">{{ paid?'✓':'◇' }}</span><h1 class="mt-5 font-serif text-3xl">{{ stateCopy[0] }}</h1><p class="mt-3 text-sm leading-6 text-muted">{{ stateCopy[1] }}</p><p v-if="returnHint && !paid && status==='pending'" class="mt-4 rounded-xl bg-accent-soft p-4 text-sm text-accent-text">{{ returnHint==='cancelled'?'You returned from checkout without completing it.':'Checkout reported a problem.' }} We still check with the provider before deciding the payment status.</p><dl class="my-7 space-y-4 border-y border-border py-6 text-sm"><div class="flex justify-between gap-4"><dt class="text-muted">Package</dt><dd class="text-right font-semibold">{{ purchase.label }}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted">{{ purchase.unit_type === 'minutes' ? 'Minutes' : 'Legacy credits' }}</dt><dd>{{ purchase.credits }}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted">Amount</dt><dd class="font-semibold">{{ pesos(purchase.amount) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted">Payment provider</dt><dd>PayMongo</dd></div></dl><p v-if="message" role="status" class="mb-4 text-sm text-accent-text">{{ message }}</p><p v-if="error" role="alert" class="mb-4 text-sm text-error">{{ error }}</p><div v-if="!paid && status==='pending'" class="flex flex-wrap items-center gap-4"><button class="action" :disabled="checking||cancelForm.processing" @click="verify">{{ checking?'Checking…':'Check payment status' }}</button><a v-if="purchase.checkout_url" :href="purchase.checkout_url" class="text-sm text-accent-text underline">Return to checkout</a><button type="button" class="text-sm text-muted underline" :disabled="checking||cancelForm.processing" @click="cancelForm.post(route('credits.cancel',purchase.id))">{{ cancelForm.processing?'Cancelling…':'Cancel checkout' }}</button></div><Link v-else :href="route('credits')" class="action inline-block">{{ paid?'View balance':'Return to Minutes' }}</Link><p v-if="status==='pending'" class="mt-5 text-xs leading-5 text-muted">Cancelling closes this request in Intuition Island. If PayMongo confirms a payment that was already completed, minutes will still be added safely.</p><p v-if="purchase.environment === 'sandbox'" class="mt-7 text-xs text-muted">Sandbox checkout · no real money charged</p><p class="mt-2 break-all font-mono text-[11px] text-muted">Reference: {{ purchase.id }}</p></div></section></AuthenticatedLayout></template>
