import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {calculateBirthChart} from '../resources/js/lib/birth-chart.mjs';
import {makeBirthChartPdf} from '../resources/js/lib/birth-chart-pdf.mjs';
import {wheelGeometry} from '../resources/js/lib/birth-chart-presentation.mjs';
const input={name:'Maria',date:'1990-07-15',time:'10:30',city:'Manila, Philippines',zone:'Asia/Manila',latitude:14.5995,longitude:120.9842};
const library=[{point:'Sun',sign:'Cancer',body:'Your Sun in Cancer shines with a nurturing glow.'},{point:'Moon',sign:'Aries',body:'Your Moon in Aries brings courage.'}];
const c=calculateBirthChart(input,library);
assert.equal(c.utc,'1990-07-15T01:30:00.000Z');assert.equal(c.offsetMinutes,540);
const expected=[['Cancer',"22°19'",11],['Aries',"17°08'",8],['Leo',"5°56'",12],['Gemini',"23°53'",10],['Taurus',"1°38'",9],['Cancer',"22°27'",11],['Capricorn',"21°59'",5],['Capricorn',"6°58'",5],['Capricorn',"12°55'",5],['Scorpio',"15°00'",3],['Aquarius',"7°21'",6],['Leo',"7°21'",12],['Virgo',"16°26'",1],['Gemini',"17°14'",10]];
assert.deepEqual(c.points.map(p=>[p.sign,p.degree,p.house]),expected);assert.equal(c.aspects.length,19);
assert.deepEqual(c.elements,{Fire:2,Earth:4,Air:1,Water:3});assert.deepEqual(c.modes,{Cardinal:6,Fixed:3,Mutable:1});assert.equal(c.readings.length,2);
assert.deepEqual(c.points.filter(p=>p.retrograde).map(p=>p.name),['Saturn','Uranus','Neptune','Pluto']);
console.log('PASS all 14 sample positions, houses, retrogrades, 19 aspects, elements and modes');
const unknown=calculateBirthChart({...input,date:'2004-06-23',unknown:true},library);
assert.deepEqual(unknown.moon.signs,['Leo','Virgo']);assert.equal(unknown.asc,null);assert.equal(unknown.mc,null);assert.equal(unknown.houses.length,0);assert.equal(unknown.aspects.length,0);assert.equal(unknown.readings.length,0);
assert.ok(unknown.points.every(p=>p.house===null));
const wheel=wheelGeometry(c);
assert.equal(wheel.signs.length,12);assert.equal(wheel.houses.length,12);
assert.equal(wheel.labels.length,12);assert.equal(wheel.angles.length,4);assert.equal(wheel.ticks.length,72);
assert.ok(wheel.signs.every(s=>s.path));assert.ok(wheel.labels.every(s=>s.path));
assert.equal(wheelGeometry(unknown),null);
assert.equal(wheel.angles[0].start.x,165);assert.ok(Math.abs(wheel.angles[0].start.y-300)<1e-8);
assert.ok(wheel.angles.find(a=>a.name==='MC').end.y<300,'sample Midheaven is above horizon');
for(const label of wheel.labels)assert.ok(Number.isFinite(label.x)&&Number.isFinite(label.y));
console.log('PASS reference-style wheel symbols, houses, angles, ticks and unknown-time guard');
const fold={...input,date:'2024-11-03',time:'01:30',zone:'America/New_York',latitude:40.71,longitude:-74};
assert.throws(()=>calculateBirthChart(fold));
assert.notEqual(calculateBirthChart({...fold,fold:'earlier'}).asc,calculateBirthChart({...fold,fold:'later'}).asc);
for(const invalid of [{date:'2100-01-01'},{date:'2000-02-30'},{latitude:90},{longitude:181},{time:'25:00'},{zone:'Not/AZone'},{name:''},{date:'2024-03-10',time:'02:30',zone:'America/New_York'}])assert.throws(()=>calculateBirthChart({...input,...invalid}));
console.log('PASS unknown time, DST fold/gap, invalid dates, coordinates and time zones');
const font=await readFile(new URL('../node_modules/@fontsource/noto-sans/files/noto-sans-latin-400-normal.woff',import.meta.url));
const dir=process.argv[2];
if(dir){await mkdir(dir,{recursive:true});
 await writeFile(dir+'/birth-chart-sample.pdf',await makeBirthChartPdf(c,font,'http://localhost:8000/bookings'));
 await writeFile(dir+'/birth-chart-unknown.pdf',await makeBirthChartPdf(unknown,font,'http://localhost:8000/bookings'));
 const stress=calculateBirthChart({...input,name:'María '.repeat(13).trim(),city:'City name '.repeat(12).trim()},library.map(r=>({...r,body:'A gentle reflection for your day. '.repeat(35)})));
 await writeFile(dir+'/birth-chart-long-text.pdf',await makeBirthChartPdf(stress,font,'http://localhost:8000/bookings'));
 console.log('PASS generated sample, unknown-time and long-text PDFs');
}
console.log('ALL BIRTH CHART CALCULATION CHECKS PASSED');
