<script setup>
import {computed,ref} from 'vue';
import {Head,Link} from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import BirthChartWheel from '@/Components/BirthChartWheel.vue';
import {calculateBirthChart} from '@/lib/birth-chart.mjs';
import {REPORT_DISCLAIMER,INVITATION} from '@/lib/birth-chart-presentation.mjs';
import fontUrl from '@fontsource/noto-sans/files/noto-sans-latin-400-normal.woff?url';
const props=defineProps({birthdate:String,reportName:String,library:Array});
const input=ref({name:props.reportName||'',date:props.birthdate||'',time:'',unknown:false,city:'',zone:'Asia/Manila',latitude:'',longitude:'',fold:''});
const consent=ref(false),coordinatesConfirmed=ref(false),chart=ref(null),error=ref(''),busy=ref(false),pdfError=ref('');
const zones=Intl.supportedValuesOf?Intl.supportedValuesOf('timeZone'):['Asia/Manila','Australia/Perth','Europe/Rome','America/New_York','UTC'];
const preset=ref('');
const places=[{name:'Manila, Philippines',latitude:14.5995,longitude:120.9842,zone:'Asia/Manila'},{name:'Marikina, Philippines',latitude:14.6507,longitude:121.1029,zone:'Asia/Manila'}];
function usePlace(){const p=places.find(p=>p.name===preset.value);if(p){input.value={...input.value,city:p.name,latitude:p.latitude,longitude:p.longitude,zone:p.zone};coordinatesConfirmed.value=false;}}
function generate(){error.value='';pdfError.value='';chart.value=null;if(!consent.value){error.value='Confirm the privacy notice first.';return;}if(!input.value.unknown&&!coordinatesConfirmed.value){error.value='Confirm the birthplace coordinates and time zone.';return;}try{chart.value=calculateBirthChart({...input.value},props.library);}catch(e){error.value=e.message;}}
const big=computed(()=>chart.value?[chart.value.points[0],chart.value.points[1],chart.value.points.find(p=>p.name==='Ascendant')]:[]);
async function download(){busy.value=true;pdfError.value='';try{const {makeBirthChartPdf}=await import('@/lib/birth-chart-pdf.mjs');const response=await fetch(fontUrl);if(!response.ok)throw new Error('The PDF font could not load. Please retry.');const bytes=await makeBirthChartPdf(chart.value,await response.arrayBuffer(),new URL('/bookings',window.location.origin).href);const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='intuition-island-birth-chart.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){pdfError.value=e.message||'Unable to create PDF. Your on-screen chart is unchanged.';}finally{busy.value=false;}}
</script>
<template><Head title="Birth Chart Studio"/><AuthenticatedLayout><main class="mx-auto max-w-7xl px-4 py-6 sm:px-6">
 <header class="mb-5"><p class="text-xs uppercase tracking-widest text-accent-text">Intuition Island · Free for registered members</p><h1 class="mt-2 font-serif text-4xl">Birth Chart Studio</h1><p class="mt-2 text-muted">Read the sky you were born under.</p></header>
 <div class="grid items-start gap-5 xl:grid-cols-[21rem_minmax(0,1fr)]">
  <form class="space-y-3 rounded-2xl border border-border bg-surface p-5" @submit.prevent="generate">
   <h2 class="font-serif text-2xl">Your birth details</h2>
   <label class="block text-sm">Name on report<input v-model="input.name" required maxlength="80" class="field mt-1 w-full"/></label>
   <label class="block text-sm">Birthdate<input v-model="input.date" required type="date" min="1900-01-01" class="field mt-1 w-full"/></label>
   <label class="flex gap-2 text-sm"><input v-model="input.unknown" type="checkbox"/>I don't know my birth time</label>
   <template v-if="!input.unknown"><label class="block text-sm">Birth time<input v-model="input.time" required type="time" class="field mt-1 w-full"/></label><details class="text-xs text-muted"><summary class="cursor-pointer">If a daylight-saving clock time occurred twice</summary><select v-model="input.fold" aria-label="Repeated clock time" class="field mt-2 w-full"><option value="">Ask me if ambiguous</option><option value="earlier">Earlier occurrence</option><option value="later">Later occurrence</option></select></details></template>
   <label class="block text-sm">City shortcut<select v-model="preset" class="field mt-1 w-full" @change="usePlace"><option value="">Enter birthplace manually</option><option v-for="p in places" :key="p.name">{{ p.name }}</option></select></label>
   <label class="block text-sm">City of birth<input v-model="input.city" required maxlength="120" class="field mt-1 w-full" placeholder="City, country"/></label>
   <label class="block text-sm">Birth time zone<select v-model="input.zone" class="field mt-1 w-full" @change="coordinatesConfirmed=false"><option v-for="z in zones" :key="z">{{ z }}</option></select></label>
   <template v-if="!input.unknown"><div class="grid grid-cols-2 gap-3"><label class="text-sm">Latitude<input v-model="input.latitude" required type="number" step="any" min="-88.9999" max="88.9999" class="field mt-1 w-full" @input="coordinatesConfirmed=false"/></label><label class="text-sm">Longitude<input v-model="input.longitude" required type="number" step="any" min="-180" max="180" class="field mt-1 w-full" @input="coordinatesConfirmed=false"/></label></div><p class="text-xs leading-5 text-muted">Shortcuts use approximate city-center coordinates. For other places, enter coordinates and the correct historical time zone. North/east are positive; south/west are negative. No external location service is contacted.</p><label class="flex gap-2 text-xs leading-5"><input v-model="coordinatesConfirmed" type="checkbox" required/>I checked the birthplace coordinates and time zone.</label></template>
   <p v-else class="rounded-lg bg-page p-3 text-xs leading-5 text-muted">Unknown time produces a limited noon-reference report. Rising, houses and aspects will not be assigned.</p>
   <label class="flex gap-2 text-xs leading-5"><input v-model="consent" type="checkbox" required/>I understand these details are used only in this browser to generate my chart and PDF. They are not saved to my account or sent to AI.</label>
   <p class="text-xs leading-5 text-muted">Your existing account birthdate is prefilled. A downloaded PDF contains personal birth details; store and share it carefully. No minutes or payment are required.</p>
   <p v-if="error" role="alert" class="text-sm text-error">{{ error }}</p><button class="action w-full">Generate my birth chart</button>
  </form>
  <section v-if="!chart" class="rounded-2xl border border-border bg-surface p-6"><h2 class="font-serif text-2xl">Your sky, in one report.</h2><p class="mt-3 text-sm leading-7 text-muted">Explore Sun, Moon and Rising, planetary positions, whole-sign houses and major aspects. Generate your chart here, then download a personal PDF.</p><p class="mt-3 text-xs leading-6 text-muted">Interpretation text appears only where an approved entry exists. Written interpretations are reviewed by the Intuition Island team and may not yet be available for every placement.</p></section>
  <section v-else class="min-w-0 space-y-4" aria-live="polite">
   <header class="rounded-2xl border border-border bg-surface p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0"><p class="text-xs text-muted">{{ chart.date }} · {{ chart.time||'Birth time unknown' }} · {{ chart.zone }}</p><h2 class="mt-1 break-words font-serif text-3xl">The Birth Chart of {{ chart.name }}</h2><p class="mt-2 break-words text-sm text-muted">{{ chart.city }} · {{ chart.unknown?'Noon reference':'Calculated for' }} {{ chart.utc }}</p></div><button class="action" :disabled="busy" @click="download">{{ busy?'Preparing PDF…':'Download PDF' }}</button></div><p v-if="pdfError" role="alert" class="mt-3 text-sm text-error">{{ pdfError }}</p><p class="mt-3 text-xs text-muted">Changing the form does not alter this report until you select Generate again.</p></header>
   <div class="grid gap-3 sm:grid-cols-3"><article v-for="(p,i) in big" :key="i" class="rounded-xl border border-border bg-surface p-4"><p class="text-xs uppercase tracking-widest text-muted">{{ ['Sun','Moon','Rising'][i] }}</p><p class="mt-1 font-serif text-2xl">{{ p?(chart.unknown&&i===1?chart.moon.signs.join(' or '):p.sign):'Unknown' }}</p><p class="mt-1 text-xs text-muted">{{ chart.unknown?(i===1?'Possible signs during the birth date':'Not confirmed without a birth time'):(p.degree+' · house '+p.house) }}</p></article></div>
   <section class="rounded-2xl border border-border bg-surface p-4"><h3 class="mb-3 font-serif text-2xl">Your birth chart wheel</h3><BirthChartWheel v-if="!chart.unknown" :chart="chart"/><p v-else class="rounded-xl border border-border bg-page p-4 text-sm leading-6">A full chart wheel needs your birth time. Enter the time, confirm the birthplace coordinates, then select Generate again to see your Rising sign, houses and aspect lines. Your approximate planetary signs are still listed below.</p><p v-if="!chart.unknown" class="mt-3 text-xs leading-6 text-muted">Outer ring: zodiac signs · Numbers: whole-sign houses · Symbols: planets and nodes · R: retrograde. AC: Rising, MC: Midheaven, DC: Descendant, IC: lower meridian. Red and green lines show major aspects. Exact degrees are listed below.</p><p v-for="w in chart.warnings" :key="w" class="mt-2 text-xs leading-6 text-muted">{{ w }}</p></section>
   <section class="overflow-hidden rounded-2xl border border-border bg-surface"><h3 class="p-4 font-serif text-2xl">Planets and points</h3><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-page text-xs text-muted"><tr><th class="p-3">Point</th><th>Sign</th><th>{{ chart.unknown?'Reference':'Degree' }}</th><th>House</th><th class="pr-3">Motion</th></tr></thead><tbody><tr v-for="(p,i) in chart.points" :key="p.name" class="border-t border-border"><td class="whitespace-nowrap p-3">{{ i+1 }}. {{ p.name }}</td><td class="pr-3">{{ chart.unknown&&p.name==='Moon'?chart.moon.signs.join(' / '):p.sign }}</td><td class="whitespace-nowrap pr-3">{{ chart.unknown?'Noon estimate':p.degree }}</td><td>{{ p.house||'—' }}</td><td class="pr-3">{{ !chart.unknown&&p.retrograde?'Retrograde':'—' }}</td></tr></tbody></table></div></section>
   <details v-if="!chart.unknown" class="rounded-2xl border border-border bg-surface p-4"><summary class="cursor-pointer font-serif text-xl">Whole-sign houses, elements and modes</summary><p class="mt-3 text-xs text-muted">{{ Object.entries(chart.elements).map(([k,v])=>k+' '+v).join(' · ') }}</p><p class="mt-2 text-xs text-muted">{{ Object.entries(chart.modes).map(([k,v])=>k+' '+v).join(' · ') }}</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><article v-for="h in chart.houses" :key="h.number" class="rounded-lg border border-border p-3"><h4 class="text-sm font-semibold">{{ h.number }} · {{ h.sign }}</h4><p class="mt-1 text-xs text-muted">{{ h.theme }}</p><p class="mt-1 text-xs">{{ h.points.join(', ')||'No listed planets or nodes' }}</p></article></div></details>
   <details v-if="!chart.unknown" class="rounded-2xl border border-border bg-surface p-4"><summary class="cursor-pointer font-serif text-xl">Major aspects · {{ chart.aspects.length }}</summary><div class="mt-3 grid gap-2 sm:grid-cols-2"><p v-for="a in chart.aspects" :key="a.a+a.b" class="text-sm">{{ a.a }} {{ a.name }} {{ a.b }} <span class="text-muted">({{ a.orb.toFixed(1) }}°)</span></p></div></details>
   <section class="rounded-2xl border border-border bg-surface p-5"><h3 class="font-serif text-2xl">Your Reading</h3><article v-for="r in chart.readings" :key="r.heading" class="mt-4"><h4 class="text-sm font-semibold text-accent-text">{{ r.heading }}</h4><p class="mt-2 whitespace-pre-wrap text-sm leading-7">{{ r.body }}</p></article><p v-if="chart.readings.length<3" class="mt-3 text-sm leading-7 text-muted">A complete written interpretation has not yet been supplied for these placements. Missing text is not invented; your calculated chart is available for a personal interpretation.</p><p class="mt-4 font-serif text-xl">May you trust the sky within you.</p><h4 class="mt-5 font-semibold">Go deeper with a personal interpretation</h4><p class="mt-2 text-sm leading-7 text-muted">{{ INVITATION }}</p><Link :href="route('bookings.index')" class="action mt-4 inline-block">Book your session</Link></section>
   <p class="text-xs leading-6 text-muted">{{ chart.method }} {{ REPORT_DISCLAIMER }}</p>
  </section>
 </div></main></AuthenticatedLayout></template>
