<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import PageLinks from '@/Components/PageLinks.vue';
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import { ref, computed, watch } from 'vue';
const props=defineProps({balance:Number,transactions:Object,shop:Object,packages:Array,paymentMethods:Array,purchases:Array});
const credits=units=>(Number(units)/3600).toLocaleString(undefined,{maximumFractionDigits:4});
const pesos=cents=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(cents/100);
const selected=ref(props.packages[0]?.id ?? null), quantity=ref(Math.max(1,Math.ceil(props.shop.minimum_amount/props.shop.price_per_credit)));
const item=computed(()=>props.packages.find(p=>p.id===selected.value));
const count=computed(()=>item.value ? item.value.credits : Number(quantity.value));
const total=computed(()=>item.value ? item.value.amount : count.value*props.shop.price_per_credit);
const canBuy=computed(()=>usePage().props.auth.user.role==='user');
const form=useForm({package_id:null,credits:null,provider:'',request_key:crypto.randomUUID(),expected_amount:0,expected_credits:0});
const method=computed(()=>props.paymentMethods.find(p=>p.id===form.provider));
const valid=computed(()=>canBuy.value && (item.value || props.shop.custom_enabled) && Number.isInteger(count.value) && count.value>=1 && count.value<=100000 && total.value>=Math.max(props.shop.minimum_amount,method.value?.minimum??100) && total.value<=10000000 && method.value?.available);
watch([selected,quantity,()=>form.provider],()=>{form.request_key=crypto.randomUUID();form.clearErrors();});
const buy=()=>{if(!valid.value)return; form.package_id=item.value?.id??null;form.credits=item.value?null:count.value;form.expected_amount=total.value;form.expected_credits=count.value;form.post(route('credits.checkout'));};
</script>
<template><Head title="Credits" /><AuthenticatedLayout><section class="mx-auto max-w-5xl px-5 py-12"><p class="text-xs uppercase tracking-widest text-accent-text">Your reading balance</p><h1 class="mt-3 font-serif text-4xl">Credits</h1><div class="my-8 rounded-2xl bg-accent-soft p-7"><p class="text-sm">Available credits</p><p class="mt-3 font-serif text-5xl">{{ balance.toLocaleString(undefined,{maximumFractionDigits:4}) }}</p></div>
    <section v-if="canBuy" class="mb-12"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-serif text-3xl">Add credits</h2><span class="rounded-full bg-accent-soft px-3 py-1 text-xs text-accent-text">Sandbox · no real payments</span></div><p class="mt-3 text-sm text-muted">Choose a package or enter the credits you need. Minimum purchase: {{ pesos(shop.minimum_amount) }}.</p>
        <fieldset class="mt-6"><legend class="sr-only">Choose a credit package</legend><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label v-for="pack in packages" :key="pack.id" class="cursor-pointer rounded-2xl border bg-surface p-5" :class="selected===pack.id ? 'border-primary ring-1 ring-primary' : 'border-border'"><div class="flex justify-between gap-3"><span class="font-semibold">{{ pack.name }}</span><input type="radio" name="credit-option" :value="pack.id" v-model="selected" /></div><p class="mt-5 text-2xl">{{ pack.credits.toLocaleString() }} <span class="text-sm text-muted">credits</span></p><p class="mt-2 font-semibold text-accent-text">{{ pesos(pack.amount) }}</p></label><label v-if="shop.custom_enabled" class="cursor-pointer rounded-2xl border bg-surface p-5" :class="selected===null ? 'border-primary ring-1 ring-primary' : 'border-border'"><div class="flex justify-between gap-3"><span class="font-semibold">Custom amount</span><input type="radio" name="credit-option" :value="null" v-model="selected" /></div><p class="mt-5 text-sm text-muted">{{ pesos(shop.price_per_credit) }} per credit</p><span class="mt-3 block text-xs text-muted">Enter your own credit quantity below.</span></label></div></fieldset>
        <p v-if="!packages.length && !shop.custom_enabled" class="mt-5 text-muted">Credit purchases are currently unavailable.</p>
        <form @submit.prevent="buy" class="mt-6 space-y-5 rounded-2xl border border-border bg-surface p-6"><label v-if="selected===null && shop.custom_enabled" class="block text-sm">How many credits?<input v-model.number="quantity" type="number" min="1" max="100000" step="1" required class="field mt-2 w-full sm:max-w-xs" /></label><div v-if="count>0 && (item || shop.custom_enabled)" class="flex flex-wrap justify-between gap-3 border-b border-border pb-4"><span>{{ Number(count).toLocaleString() }} credits</span><strong>{{ pesos(total) }} total</strong></div>
            <fieldset><legend class="mb-3 text-sm font-semibold">Payment method</legend><div class="grid gap-3 sm:grid-cols-3"><label v-for="pay in paymentMethods" :key="pay.id" class="rounded-xl border border-border p-4" :class="pay.available ? 'cursor-pointer' : 'opacity-60'"><div class="flex items-center justify-between gap-2"><span class="text-sm">{{ pay.name }}</span><input type="radio" name="payment-method" :value="pay.id" v-model="form.provider" :disabled="!pay.available" /></div><p class="mt-2 text-xs text-muted">{{ pay.available ? 'Test checkout' : 'Not connected yet' }}</p><p v-if="pay.minimum>shop.minimum_amount" class="mt-1 text-xs text-muted">Minimum {{ pesos(pay.minimum) }}</p></label></div></fieldset>
            <p v-if="!paymentMethods.some(p=>p.available)" class="text-sm text-muted">Online payment is being set up. An administrator can still add credits manually.</p><p v-if="total<Math.max(shop.minimum_amount,method?.minimum??100)" class="text-sm text-error">Choose enough credits to meet the minimum of {{ pesos(Math.max(shop.minimum_amount,method?.minimum??100)) }}.</p><p v-for="e in form.errors" :key="e" role="alert" class="text-sm text-error">{{ e }}</p><button class="action w-full sm:w-auto" :disabled="!valid || form.processing">{{ form.processing ? 'Opening checkout…' : 'Continue to test payment' }}</button><p class="text-xs text-muted">Credits are added only after the payment provider confirms success.</p>
        </form>
    </section>
    <section v-if="purchases.length" class="mb-10"><h2 class="mb-4 font-serif text-2xl">Recent purchases</h2><Link v-for="purchase in purchases" :key="purchase.id" :href="route('credits.purchase',purchase.id)" class="mb-3 flex flex-wrap justify-between gap-3 rounded-xl border border-border bg-surface p-4"><span>{{ purchase.label }} · {{ purchase.credits }} credits</span><span class="text-sm text-muted">{{ pesos(purchase.amount) }} · {{ purchase.status.replaceAll('_',' ') }} →</span></Link></section>
    <h2 class="mb-5 font-serif text-2xl">Transaction history</h2><article v-for="t in transactions.data" :key="t.id" class="mb-3 flex flex-wrap justify-between gap-4 rounded-xl border border-border bg-surface p-5"><div><p class="capitalize">{{ t.kind.replaceAll('_',' ') }}</p><p class="text-sm text-muted">{{ t.reason }}</p><p class="text-xs text-muted">{{ t.created_at }} UTC</p></div><div class="text-right"><p>{{ credits(t.amount_units) }} credits</p><p class="text-xs text-muted">Balance after: {{ credits(t.balance_units) }}</p></div></article><PageLinks :data="transactions" />
</section></AuthenticatedLayout></template>
