<script setup>
import { ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import Modal from '@/Components/Modal.vue';
import PageLinks from '@/Components/PageLinks.vue';
import StatusNotice from '@/Components/StatusNotice.vue';
defineProps({applications:Object});
const selected=ref(null);
const form=useForm({decision:'approved',review_note:'',rate_per_hour:null});
const review=(application)=>{selected.value=application;form.reset();form.clearErrors();};
const submit=()=>form.patch(route('admin.application.review',selected.value.id),{preserveScroll:true,onSuccess:()=>selected.value=null});
</script>
<template><section><h2 class="font-serif text-2xl">Counselor applications</h2><p class="mb-6 mt-2 text-sm text-muted">Review qualifications and approve access here. Pending applications appear first.</p>
<StatusNotice v-if="!applications.data.length">No counselor applications yet.</StatusNotice>
<article v-for="a in applications.data" :key="a.id" class="mb-5 rounded-2xl border border-border bg-surface p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h3 class="text-lg font-semibold">{{ a.name }}</h3><p class="break-all text-sm text-muted">{{ a.email }}</p></div><span class="rounded-full bg-accent-soft px-3 py-1 text-xs capitalize text-accent-text">{{ a.status }}</span></div><p class="mt-4 text-sm text-muted">{{ a.specialties }} · {{ a.years_experience }} years of experience</p><details class="mt-4"><summary class="cursor-pointer text-sm font-semibold text-accent-text">Read application</summary><dl class="mt-4 space-y-4 text-sm"><div v-for="[key,label] in [['biography','Introduction'],['languages','Languages'],['qualifications','Experience & qualifications (private)'],['availability','Availability'],['review_note','Review feedback']]" :key="key"><dt class="font-semibold">{{ label }}</dt><dd class="mt-1 whitespace-pre-wrap break-words leading-6 text-muted">{{ a[key] || '—' }}</dd></div></dl></details><button v-if="a.status==='pending'" class="action mt-5" @click="review(a)">Review application</button></article><PageLinks :data="applications" />
<Modal :show="Boolean(selected)" :closeable="!form.processing" @close="selected=null"><form @submit.prevent="submit" class="space-y-5 p-6 sm:p-8"><h2 class="font-serif text-2xl">Review {{ selected?.name }}</h2><label class="block text-sm font-semibold">Decision<select v-model="form.decision" class="field mt-2 w-full"><option value="approved">Approve counselor access</option><option value="rejected">Decline with feedback</option></select></label><label v-if="form.decision==='approved'" class="block text-sm font-semibold">Credits per hour (optional)<input v-model="form.rate_per_hour" type="number" min="1" max="100000" class="field mt-2 w-full" /><span class="mt-2 block text-xs font-normal text-muted">Leave blank to use the default rate in Pricing & Billing.</span></label><label class="block text-sm font-semibold">Feedback for the applicant<textarea v-model="form.review_note" required minlength="5" maxlength="1000" rows="4" class="field mt-2 w-full"></textarea></label><p class="text-xs leading-5 text-muted">Approval changes this account to Counselor and makes its profile available. The decision is recorded in Audit History.</p><p v-for="e in form.errors" :key="e" role="alert" class="text-sm text-error">{{ e }}</p><div class="flex flex-wrap gap-3"><button type="button" class="rounded-full border border-border px-5 py-3" :disabled="form.processing" @click="selected=null">Cancel</button><button class="action" :disabled="form.processing">{{ form.processing ? 'Saving…' : 'Confirm decision' }}</button></div></form></Modal>
</section></template>
