<script setup>
import { useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import Modal from '@/Components/Modal.vue';
const props=defineProps({shop:Object,packages:Array,paymentMethods:Array});
const pesos=cents=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(cents/100);
const packageForm=useForm({id:null,name:'',credits:1,price:'1.00',active:true}); const editing=ref(false);
const extraForm=useForm({custom_enabled:true,price:(props.shop.extra_minute_amount/100).toFixed(2),minimum:(props.shop.minimum_amount/100).toFixed(2)});
const edit=item=>{ packageForm.reset(); packageForm.clearErrors(); if(item)Object.assign(packageForm,{id:item.id,name:item.name,credits:item.credits,price:(item.amount/100).toFixed(2),active:!!item.active}); editing.value=true; };
</script>
<template>
    <section class="mt-10 border-t border-border pt-9"><h2 class="font-serif text-3xl">Minute purchases</h2><p class="mt-3 text-sm text-muted">Fixed PHP prices. Every coach uses one purchased minute per reading minute; sessions round up once when ended.</p>
        <section class="mt-6 max-w-xl rounded-2xl border border-border bg-surface p-6"><h3 class="text-lg font-semibold">Extra-time pricing</h3><p class="mt-2 text-sm text-muted">Customers separately authorize and pay upfront for extra minutes. No automatic card charges. Conversion baseline: ₱{{ shop.conversion_rate }} per USD, {{ shop.conversion_date }}.</p><form @submit.prevent="extraForm.patch(route('admin.shop'),{preserveScroll:true})" class="mt-3 flex flex-wrap items-end gap-3"><label class="text-sm">PHP per extra minute<input v-model="extraForm.price" type="number" min="0.01" max="100000" step="0.01" required class="field mt-1 block w-36" /></label><button class="action" :disabled="extraForm.processing">Save</button><p v-for="e in extraForm.errors" :key="e" class="text-error">{{ e }}</p></form></section>
        <div class="mb-4 mt-9 flex flex-wrap items-center justify-between gap-3"><h3 class="font-serif text-2xl">Minute packages</h3><button type="button" class="action" @click="edit(null)">Add package</button></div>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article v-for="item in packages.filter(p => p.unit_type === 'minutes')" :key="item.id" class="rounded-2xl border border-border bg-surface p-5"><p class="text-xs text-accent-text">{{ !item.active ? 'Hidden' : item.amount < shop.minimum_amount ? 'Below shop minimum' : 'Visible to users' }}</p><h4 class="mt-2 font-semibold">{{ item.name }}</h4><p v-if="item.welcome" class="mt-1 text-xs text-muted">Welcome offer · once per person</p><p class="mt-3 text-xl">{{ item.credits.toLocaleString() }} minutes</p><p class="mt-1 text-muted">{{ pesos(item.amount) }} total</p><button class="mt-4 text-sm text-accent-text underline" @click="edit(item)">Edit package</button></article></div><p v-if="!packages.length" class="text-muted">Add a package to offer a preset minute amount.</p>
        <div class="mt-8 rounded-2xl border border-border p-5"><h3 class="font-semibold">Payment connections · sandbox only</h3><p class="mt-2 text-sm text-muted">Test payments do not move real money. Merchant credentials are configured securely on the server.</p><ul class="mt-4 space-y-2 text-sm"><li v-for="method in paymentMethods" :key="method.id">{{ method.name }} — {{ method.available ? 'Sandbox configured' : 'Not connected' }} · configured minimum {{ pesos(method.minimum) }}</li></ul></div>
        <Modal :show="editing" :closeable="!packageForm.processing" @close="editing=false"><form @submit.prevent="packageForm.post(route('admin.package'),{preserveScroll:true,onSuccess:()=>editing=false})" class="space-y-5 p-6"><h2 class="font-serif text-2xl">{{ packageForm.id ? 'Edit package' : 'New package' }}</h2><label class="block">Package name<input v-model="packageForm.name" required maxlength="100" class="field mt-2 w-full" placeholder="Example: Starter minutes" /></label><label class="block">Minutes included<input v-model.number="packageForm.credits" type="number" min="1" max="100000" step="1" required class="field mt-2 w-full" /></label><label class="block">Total price (₱)<input v-model="packageForm.price" type="number" min="1" max="100000" step="0.01" required class="field mt-2 w-full" /></label><label class="flex gap-3"><input v-model="packageForm.active" type="checkbox" /> Show on the Minutes page</label><p class="text-xs text-muted">Uncheck to hide this package. Existing purchases retain their original minutes and price.</p><p v-for="e in packageForm.errors" :key="e" role="alert" class="text-error">{{ e }}</p><div class="flex gap-3"><button type="button" class="rounded-full border border-border px-5 py-3" :disabled="packageForm.processing" @click="editing=false">Cancel</button><button class="action" :disabled="packageForm.processing">Save package</button></div></form></Modal>
    </section>
</template>
