<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import { Link } from '@inertiajs/vue3';
import axios from 'axios';
const open=ref(false),items=ref([]),unread=ref(0),loading=ref(false),error=ref(''),panel=ref(null),trigger=ref(null);
let timer,stopped=false;
const refresh=async()=>{if(loading.value||document.hidden)return;loading.value=true;try{const {data}=await axios.get(route('notifications.index'));if(!stopped){items.value=data.items;unread.value=data.unread;error.value='';}}catch{if(!stopped)error.value='Notifications could not be loaded. Try again.';}finally{loading.value=false;}};
const read=async(id=null)=>{try{await axios.post(route('notifications.read'),{id});await refresh();}catch{error.value='Could not mark notifications as read. Please retry.';}};
const close=()=>{open.value=false;trigger.value?.focus();};
const outside=e=>{if(open.value&&!panel.value?.contains(e.target))open.value=false;};
onMounted(()=>{refresh();timer=setInterval(refresh,30000);document.addEventListener('pointerdown',outside);window.addEventListener('focus',refresh);});
onUnmounted(()=>{stopped=true;clearInterval(timer);document.removeEventListener('pointerdown',outside);window.removeEventListener('focus',refresh);});
</script>
<template><div ref="panel" class="relative" @keydown.esc="close"><button ref="trigger" type="button" class="relative rounded-full border border-border p-2.5 text-accent-text hover:bg-surface-hover" :aria-label="'Notifications, '+unread+' unread'" :aria-expanded="open" aria-controls="notifications-panel" @click="open=!open; if(open) refresh()"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 21h6" /></svg><span v-if="unread" class="absolute -right-1 -top-1 rounded-full bg-primary px-1.5 text-[10px] text-on-primary">{{ unread>99?'99+':unread }}</span></button><section v-if="open" id="notifications-panel" aria-label="Notifications" class="fixed left-3 right-3 top-20 z-50 max-h-[75dvh] overflow-y-auto rounded-2xl border border-border bg-surface p-4 shadow-xl sm:absolute sm:left-auto sm:right-0 sm:top-12 sm:w-96"><div class="flex items-center justify-between gap-3"><h2 class="font-serif text-xl">Notifications</h2><button type="button" class="text-xs text-accent-text underline" @click="close">Close</button></div><button v-if="unread" class="mt-3 text-xs text-accent-text underline" @click="read()">Mark all as read</button><p v-if="loading && !items.length" class="py-6 text-sm text-muted" role="status">Loading notifications…</p><div v-if="error" class="py-4 text-sm text-error" role="alert">{{ error }} <button class="underline" @click="refresh">Retry</button></div><p v-if="!items.length && !loading && !error" class="py-6 text-sm text-muted">You’re all caught up. Reading, payment, and application updates will appear here.</p><article v-for="item in items" :key="item.id" class="mt-3 rounded-xl border border-border p-3" :class="item.read_at?'':'bg-accent-soft'"><Link :href="item.url" class="block" @click="read(item.id);open=false"><h3 class="text-sm font-semibold">{{ item.title }} <span v-if="!item.read_at" class="sr-only">Unread</span></h3><p class="mt-1 whitespace-pre-wrap text-xs leading-5 text-muted">{{ item.body }}</p></Link></article></section></div></template>
