<script setup>
import {ref} from 'vue';
import {Head,Link,useForm,usePage} from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminWorkspace from '@/Components/AdminWorkspace.vue';
import PageLinks from '@/Components/PageLinks.vue';
import Modal from '@/Components/Modal.vue';
defineProps({requests:Object,notice:Object});
const admin=usePage().props.auth.user.role==='admin';
const form=useForm({kind:'transcripts',chat_session_id:null,reason:'',consent:false,password:''});
const selected=ref(null),decision=useForm({approve:false,confirm:false,reason:''});
</script>
<template><Head title="Privacy requests" /><AuthenticatedLayout><component :is="admin?AdminWorkspace:'main'" section="privacy" :class="admin?'':'mx-auto max-w-4xl px-4 py-6'">
 <h1 v-if="!admin" class="font-serif text-3xl">Privacy & account requests</h1><p class="mb-4 mt-2 text-sm text-muted">Download your transcripts before requesting deletion. <Link :href="route('chat.index')" class="text-accent-text underline">Open conversations</Link></p>
 <p v-if="notice?.delete_after" class="mb-4 rounded-xl bg-accent-soft p-3 text-sm">Your saved chat messages and attachments are scheduled for deletion on {{notice.delete_after}} UTC. A new paid session or confirmed purchase resets the inactivity clock.</p>
 <form v-if="!admin" @submit.prevent="form.post(route('privacy.requests.store'),{preserveScroll:true,onSuccess:()=>form.reset()})" class="mb-5 space-y-3 rounded-2xl border border-border bg-surface p-4"><label class="block text-sm">Request<select v-model="form.kind" class="field mt-1 w-full"><option value="transcripts">Delete chat transcripts and attachments</option><option value="account">Close my account</option></select></label><label v-if="form.kind==='transcripts'" class="block text-sm">Conversation / reading ID (optional)<input v-model="form.chat_session_id" type="number" min="1" class="field mt-1 w-full" /><span class="mt-1 block text-xs text-muted">Leave blank for all your conversations. Only messages already present when you submit are included.</span></label><label class="block text-sm">Details<textarea v-model="form.reason" required minlength="10" maxlength="1000" rows="3" class="field mt-1 w-full" /></label><label v-if="form.kind==='account'" class="block text-sm">Confirm password<input v-model="form.password" type="password" autocomplete="current-password" required class="field mt-1 w-full" /></label>
 <p class="text-xs leading-5 text-muted">Admins review requests before acting. Chat deletion removes the shared transcript and attachments for both participants, not exported copies. Financial records, support messages, and private coach notes are outside this deletion workflow.</p><p v-if="form.kind==='account'" class="text-xs leading-5 text-error">Account closure cancels bookings, forfeits remaining minutes, deletes chats and the profile photo, anonymizes login details, and disables access. A pseudonymous account record and the excluded records above remain. This is not a cash refund.</p>
 <label class="flex items-start gap-2 text-xs"><input v-model="form.consent" type="checkbox" required />I understand these consequences and request admin review.</label><p v-for="e in form.errors" :key="e" role="alert" class="text-error">{{e}}</p><button class="action !py-2 text-sm" :disabled="form.processing||!form.consent">Submit request</button></form>
 <section class="space-y-3"><h2 class="font-serif text-xl">{{admin?'Requests to review':'Your requests'}}</h2><article v-for="r in requests.data" :key="r.id" class="rounded-xl border border-border bg-surface p-4 text-sm"><div class="flex flex-wrap justify-between gap-2"><strong>#{{r.id}} · {{r.kind==='account'?'Account closure':'Transcript deletion'}}<span v-if="admin"> · {{r.name}}</span></strong><span class="capitalize text-accent-text">{{r.status}}</span></div><p class="mt-2 whitespace-pre-wrap break-words text-muted">{{r.reason}}</p><p v-if="r.decision_reason" class="mt-2">Decision: {{r.decision_reason}}</p><button v-if="admin&&r.status==='pending'" class="mt-3 text-accent-text underline" @click="selected=r;decision.reset()">Review request</button></article><p v-if="!requests.data.length" class="text-sm text-muted">No requests yet.</p><PageLinks :data="requests" /></section>
 <Modal :show="!!selected" max-width="md" @close="selected=null"><form @submit.prevent="decision.post(route('privacy.requests.review',selected.id),{preserveScroll:true,onSuccess:()=>selected=null})" class="space-y-3 p-5"><h2 class="font-serif text-xl">Review privacy request</h2><label class="block text-sm">Decision<select v-model="decision.approve" class="field mt-1 w-full"><option :value="false">Decline / needs clarification</option><option :value="true">Approve irreversible deletion / closure</option></select></label><label class="block text-sm">Reason<textarea v-model="decision.reason" minlength="10" maxlength="1000" required rows="3" class="field mt-1 w-full" /></label><label class="flex gap-2 text-xs"><input v-model="decision.confirm" type="checkbox" required />I reviewed the request, shared-chat consequences, and retained-record exclusions.</label><p v-for="e in decision.errors" :key="e" class="text-error">{{e}}</p><div class="flex justify-end gap-3"><button type="button" @click="selected=null">Cancel</button><button class="action !py-2" :disabled="!decision.confirm||decision.processing">Confirm decision</button></div></form></Modal>
 </component></AuthenticatedLayout></template>
