<script setup>
import { computed } from 'vue';
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import PageHeader from '@/Components/PageHeader.vue';
import StatusNotice from '@/Components/StatusNotice.vue';
import InputError from '@/Components/InputError.vue';
const props=defineProps({application:Object});
const canSubmit=computed(()=>usePage().props.auth.user.role==='user' && (!props.application || props.application.status==='rejected'));
const form=useForm({biography:props.application?.biography||'',specialties:props.application?.specialties||'',languages:props.application?.languages||'',years_experience:props.application?.years_experience??0,qualifications:props.application?.qualifications||'',availability:props.application?.availability||'',consent:false});
const fields=[{key:'biography',label:'Your introduction',hint:'80–2,000 characters. Introduce your approach to readings. This will appear on your approved profile.',min:80,max:2000,rows:5},{key:'specialties',label:'Specialties',hint:'For example: tarot, relationships, or personal reflection.',max:200},{key:'languages',label:'Languages',hint:'Languages you can comfortably use during a reading.',max:200},{key:'qualifications',label:'Experience & qualifications',hint:'Describe your background and training. Only administrators can see this field. Do not include identity documents or financial details.',min:10,max:2000,rows:4},{key:'availability',label:'Typical availability',hint:'Include your time zone and usual days or hours. This is guidance, not a booking guarantee.',min:5,max:500,rows:3}];
</script>
<template><Head title="Become a Counselor" /><AuthenticatedLayout><main class="mx-auto max-w-5xl px-5 py-12 sm:px-8">
<PageHeader eyebrow="Share your perspective" title="Become a Counselor" description="Tell us about your experience and the guidance you offer. Your account stays a User account until an administrator approves your application." />
<StatusNotice v-if="application" class="mb-7"><strong class="capitalize">Application {{ application.status }}</strong><p class="mt-1">{{ application.status==='pending' ? 'Your application is waiting for review. We’ll notify you here when a decision is made.' : application.status==='approved' ? 'Your application was approved. Your account permissions are shown in your profile.' : 'Review the feedback below before submitting an updated application.' }}</p><p v-if="application.review_note" class="mt-3 whitespace-pre-wrap">{{ application.review_note }}</p></StatusNotice>
<div class="grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_16rem]">
<form v-if="canSubmit" @submit.prevent="form.post(route('counselor.submit'),{preserveScroll:true})" class="space-y-6 rounded-3xl border border-border bg-surface p-6 sm:p-8">
<div v-for="field in fields" :key="field.key"><label :for="field.key" class="block text-sm font-semibold">{{ field.label }}</label><p :id="field.key+'-hint'" class="mt-1 text-xs leading-5 text-muted">{{ field.hint }}</p><textarea v-if="field.rows" :id="field.key" v-model="form[field.key]" :rows="field.rows" :minlength="field.min" :maxlength="field.max" required class="field mt-2 w-full" :aria-describedby="field.key+'-hint '+field.key+'-error'" :aria-invalid="Boolean(form.errors[field.key])"></textarea><input v-else :id="field.key" v-model="form[field.key]" :maxlength="field.max" required class="field mt-2 w-full" :aria-describedby="field.key+'-hint '+field.key+'-error'" :aria-invalid="Boolean(form.errors[field.key])" /><InputError :id="field.key+'-error'" :message="form.errors[field.key]" class="mt-2" /></div>
<label class="block text-sm font-semibold">Years of experience<input v-model.number="form.years_experience" type="number" min="0" max="60" required class="field mt-2 w-full" /><InputError :message="form.errors.years_experience" class="mt-2" /></label>
<label class="flex items-start gap-3 text-sm leading-6"><input v-model="form.consent" type="checkbox" required class="mt-1 rounded border-border text-primary focus:ring-primary" /><span>I confirm this information is accurate and agree that my introduction, specialties, languages, experience, and availability may be shown on my approved counselor profile.</span></label><InputError :message="form.errors.consent" /><InputError :message="form.errors.application || form.errors.request" />
<button class="action w-full" :disabled="form.processing">{{ form.processing ? 'Submitting…' : application ? 'Resubmit application' : 'Submit application' }}</button>
</form>
<section v-else class="space-y-5 rounded-3xl border border-border bg-surface p-7"><h2 class="font-serif text-2xl">Your application</h2><div v-for="field in fields" :key="field.key"><h3 class="text-sm font-semibold">{{ field.label }}</h3><p class="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-muted">{{ application?.[field.key] || 'No application details available.' }}</p></div><Link v-if="$page.props.auth.user.role==='counselor'" :href="route('counselor.profile',$page.props.auth.user.id)" class="inline-block text-accent-text underline">View your counselor profile</Link></section>
<aside class="rounded-2xl bg-accent-soft p-6 text-sm leading-7"><h2 class="font-serif text-2xl">What happens next?</h2><ol class="mt-4 list-decimal space-y-3 pl-5 text-muted"><li>An administrator reviews your application.</li><li>You receive a decision and feedback in Notifications.</li><li>After approval, your profile appears in Find Psychic and Earnings becomes available.</li></ol><p class="mt-5 text-xs text-muted">Rates are set by the administrator. Finish any open readings before your account is approved.</p></aside>
</div></main></AuthenticatedLayout></template>
