<script setup>
import {ref,watch} from 'vue';
import {Head,Link,router,useForm} from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminWorkspace from '@/Components/AdminWorkspace.vue';
import PageLinks from '@/Components/PageLinks.vue';
const props=defineProps({date:String,mode:String,aiReady:Boolean,day:Object,templates:Array,themes:Array,signs:Array,days:Object});
const settings=useForm({mode:props.mode}),date=ref(props.date);
const generate=useForm({date:props.date,consent:false});
const edit=useForm({version:props.day?.version||1,lines:props.day?.lines||[],action:'save',reviewed:false});
const templates=useForm({templates:props.templates.map(t=>({body:t.body||''}))});
const preview=ref(false),copied=ref(false);
watch(()=>props.day,d=>{edit.version=d?.version||1;edit.lines=JSON.parse(JSON.stringify(d?.lines||[]));edit.reviewed=false;},{deep:true});
function openDate(){router.get(route('admin.moonoscope'),{date:date.value});}
function save(action){edit.action=action;edit.put(route('admin.moonoscope.save',props.day.id),{preserveScroll:true});}
async function copy(){try{await navigator.clipboard.writeText(props.day.prompt);copied.value=true;}catch{copied.value=false;}}
const count=t=>(t.trim().match(/\S+/g)||[]).length;
</script>
<template>
 <Head title="Moonoscope administration"/><AuthenticatedLayout><AdminWorkspace section="moonoscope">
  <p v-if="$page.props.flash?.success" role="status" class="mb-4 text-sm text-accent-text">{{ $page.props.flash.success }}</p>
  <form class="flex flex-wrap items-end gap-3 rounded-xl border border-border bg-page p-4" @submit.prevent="settings.patch(route('admin.moonoscope.settings'),{preserveScroll:true})"><label class="text-sm">Content mode<select v-model="settings.mode" class="field mt-1 block"><option value="manual">Manual</option><option value="templates">Templates</option><option value="ai">AI-assisted · Claude</option></select></label><button class="action" :disabled="settings.processing">Save mode</button><p class="max-w-md text-xs leading-5 text-muted">Applies to newly created dates only. Published content and drafts are never replaced by switching modes. {{ aiReady?'AI is configured; drafting may incur provider charges.':'AI is not configured. A server API key and model are required.' }}</p></form>
  <p v-for="e in settings.errors" :key="e" role="alert" class="mt-2 text-error">{{ e }}</p>
  <form class="my-5 flex flex-wrap items-end gap-3" @submit.prevent="openDate"><label class="text-sm">Reading date<input v-model="date" type="date" required min="1900-01-01" max="2100-12-30" class="field mt-1 block"/></label><button class="action">Open date</button><span class="text-xs text-muted">Calculated at 6 AM Asia/Manila · {{ mode }}</span></form>
  <form v-if="!day" class="rounded-xl border border-border p-4" @submit.prevent="generate.post(route('admin.moonoscope.generate'))"><h3 class="font-serif text-xl">Prepare {{ props.date }}</h3><p class="mt-2 text-sm text-muted">{{ mode==='manual'?'Calculate the sky facts and open 12 blank messages.':mode==='templates'?'Fill each sign from its house template. Missing templates stay blank for review.':'Send calculated sky facts—not user birth details—to Claude to draft 12 messages.' }}</p><label class="my-3 flex gap-2 text-sm"><input v-model="generate.consent" type="checkbox" required/>{{ mode==='ai'?'I authorize this AI draft request and any provider usage charge.':'Prepare this date without changing existing publications.' }}</label><p v-for="e in generate.errors" :key="e" role="alert" class="mb-2 text-error">{{ e }}</p><button class="action" :disabled="generate.processing||(mode==='ai'&&!aiReady)">{{ generate.processing?'Preparing…':'Prepare daily draft' }}</button></form>
  <section v-else>
   <div class="rounded-xl border border-border bg-page p-4"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-serif text-xl">{{ day.facts.sign }} · {{ day.facts.degree }}° · {{ day.facts.phase }}</h3><span class="text-xs text-muted">{{ day.published_at?'Published snapshot exists':'Draft only' }} · version {{ day.version }}</span></div><p v-for="c in day.facts.changes" :key="c.utc" class="mt-2 text-xs text-muted">{{ c.from }} → {{ c.to }} · {{ new Date(c.utc).toLocaleString(undefined,{timeZone:'Asia/Manila'}) }} Manila time</p></div>
   <details class="my-3 rounded-xl border border-border p-3"><summary class="cursor-pointer text-sm">Calculated facts and writer prompt</summary><button class="mt-3 text-sm text-accent-text underline" @click="copy">{{ copied?'Copied':'Copy prompt' }}</button><pre class="mt-3 max-h-64 overflow-auto whitespace-pre-wrap text-xs">{{ day.prompt }}</pre></details>
   <div class="my-3 flex gap-3 text-sm"><button class="text-accent-text underline" @click="preview=!preview">{{ preview?'Edit messages':'Preview draft' }}</button><Link :href="route('forecast')" class="text-accent-text underline">Public page</Link></div>
   <div class="grid gap-3 md:grid-cols-2"><article v-for="(line,i) in edit.lines" :key="line.sign" class="rounded-xl border border-border bg-page/60 p-4"><div class="flex justify-between gap-2"><h3 class="font-serif text-xl">{{ line.sign }} Moon</h3><span class="text-xs" :class="count(line.text)>35?'text-error':'text-muted'">{{ count(line.text) }}/35</span></div><p class="my-2 text-xs text-muted">House {{ day.facts.houses[i].house }} · {{ day.facts.houses[i].theme }}</p><p v-if="preview" class="text-sm leading-7">{{ line.text||'Message needed before publication.' }}</p><textarea v-else v-model="line.text" :aria-label="line.sign+' message'" rows="3" maxlength="1000" class="field w-full text-sm"/></article></div>
   <div class="mt-4 rounded-xl border border-border p-4"><p class="text-sm font-semibold">Before publishing</p><p class="mt-2 text-xs leading-6 text-muted">Check the date and sky facts. Each line must be one or two positive sentences, give a small doable action, and use distinct wording. No fear, warnings, emojis, or promised health, money, legal or relationship outcomes. On sign-change days, check that each message works for the whole day.</p><label class="my-3 flex gap-2 text-sm"><input v-model="edit.reviewed" type="checkbox"/>I reviewed all 12 messages against the client's checklist.</label><p v-for="e in edit.errors" :key="e" role="alert" class="mb-2 text-error">{{ e }}</p><div class="flex flex-wrap gap-3"><button class="action" :disabled="edit.processing" @click="save('save')">Save draft</button><button class="action" :disabled="edit.processing||!edit.reviewed" @click="save('publish')">Publish approved set</button><button v-if="day.published_at" class="text-sm text-error underline" :disabled="edit.processing" @click="save('unpublish')">Unpublish</button></div><p class="mt-3 text-xs text-muted">Saving a draft does not alter published messages. Future approved sets appear on their Manila reading date.</p></div>
  </section>
  <details class="mt-5 rounded-xl border border-border p-4"><summary class="cursor-pointer font-semibold">Template library · 12 house themes</summary><p class="mt-3 text-xs leading-6 text-muted">Only three illustrative examples were supplied in the reference (houses 5, 6 and 11). The other templates need client-approved text. Templates repeat by house; they are not fresh AI readings. Review Moon mood and sign changes before publication.</p><form @submit.prevent="templates.put(route('admin.moonoscope.templates'),{preserveScroll:true})"><div class="mt-3 grid gap-3 md:grid-cols-2"><label v-for="(t,i) in templates.templates" :key="i" class="text-sm">{{ i+1 }} · {{ themes[i] }}<textarea v-model="t.body" rows="3" maxlength="1000" class="field mt-1 w-full"/><span class="text-xs text-muted">{{ count(t.body) }}/35 words</span></label></div><p v-for="e in templates.errors" :key="e" class="text-error">{{ e }}</p><button class="action mt-3" :disabled="templates.processing">Save templates</button></form></details>
  <section class="mt-5"><h3 class="font-serif text-xl">Daily sets</h3><div v-for="d in days.data" :key="d.reading_date" class="flex justify-between border-b border-border py-3 text-sm"><Link :href="route('admin.moonoscope',{date:d.reading_date})" class="text-accent-text underline">{{ d.reading_date }}</Link><span class="text-muted">{{ d.mode }} · {{ d.published_at?'Approved':'Draft' }}</span></div><PageLinks :data="days"/></section>
 </AdminWorkspace></AuthenticatedLayout>
</template>
