<script setup>
import { Head, Link, router, useForm, usePage } from '@inertiajs/vue3';
import { ref } from 'vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminWorkspace from '@/Components/AdminWorkspace.vue';
import PageLinks from '@/Components/PageLinks.vue';
import Modal from '@/Components/Modal.vue';
const props=defineProps({coaches:Object,coach:Object,reviews:Object,summary:Object,filters:Object});
const search=ref(props.filters?.q||''),selected=ref(null),page=usePage();
const form=useForm({action:'reviewed',reason:''});
const open=(review,action)=>{selected.value=review;form.reset();form.clearErrors();form.action=action;};
const save=()=>form.patch(route('admin.reviews.moderate',selected.value.id),{preserveScroll:true,onSuccess:()=>selected.value=null});
</script>
<template><Head title="Coach reviews" /><AuthenticatedLayout><AdminWorkspace section="reviews">
<p v-if="page.props.flash?.success" role="status" class="mb-5 rounded-xl bg-accent-soft p-4 text-sm">{{ page.props.flash.success }}</p>
<template v-if="!coach"><form class="mb-6 flex gap-3" @submit.prevent="router.get(route('admin.reviews'),{q:search},{preserveState:true})"><label class="min-w-0 flex-1"><span class="sr-only">Search coaches</span><input v-model="search" placeholder="Search Spiritual Coaches…" class="field w-full" /></label><button class="action">Search</button></form><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Link v-for="item in coaches.data" :key="item.id" :href="route('admin.reviews.coach',item.id)" class="rounded-2xl border border-border bg-surface p-5 hover:bg-surface-hover"><h2 class="font-serif text-xl">{{ item.name }}</h2><p class="mt-3 text-accent-text">★ {{ Number(item.review_count) ? Number(item.rating_average).toFixed(1)+' / 5' : 'Not rated yet' }}</p><p class="mt-2 text-xs text-muted">{{ item.review_count }} reviews · {{ item.pending_count }} awaiting review</p><p class="mt-5 text-sm font-semibold text-accent-text">Manage reviews</p></Link></div><p v-if="!coaches.data.length" class="py-10 text-center text-muted">No coaches found.</p><PageLinks :data="coaches" /></template>
<template v-else><Link :href="route('admin.reviews')" class="text-sm text-accent-text underline">Back to coaches</Link><h2 class="mt-5 font-serif text-3xl">{{ coach.name }}</h2><p class="mt-2 text-sm text-muted">★ {{ summary.count?summary.average.toFixed(1):'—' }} / 5 · {{ summary.count }} reviews</p><div class="mt-6 space-y-4"><article v-for="review in reviews.data" :key="review.id" class="rounded-2xl border border-border bg-surface p-5"><div class="flex flex-wrap justify-between gap-3"><span class="text-accent-text" :aria-label="`${review.rating} out of 5 stars`">{{ '★'.repeat(review.rating) }}{{ '☆'.repeat(5-review.rating) }}</span><span class="text-xs text-muted">{{ review.highlighted?'Highlighted':review.reviewed_at?'Reviewed':'Awaiting review' }}</span></div><p class="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{{ review.comment }}</p><p class="mt-3 text-xs text-muted">Reading #{{ review.chat_session_id }} · Client #{{ review.client_id }} · {{ new Date(review.created_at).toLocaleString() }}</p><p class="mt-2 text-xs text-muted">{{ review.publish_consent?'Permission to publish granted':'Private comment — publishing not permitted' }}</p><div class="mt-4 flex flex-wrap gap-3 text-sm"><button v-if="!review.reviewed_at" class="text-accent-text underline" @click="open(review,'reviewed')">Mark reviewed</button><button v-if="review.publish_consent" class="text-accent-text underline" @click="open(review,review.highlighted?'unhighlight':'highlight')">{{ review.highlighted?'Remove highlight':'Highlight on profile' }}</button><button class="text-error underline" @click="open(review,'delete')">Delete review</button></div></article><p v-if="!reviews.data.length" class="py-8 text-muted">No reviews for this coach yet.</p></div><PageLinks :data="reviews" /></template>
<Modal :show="!!selected" :closeable="!form.processing" @close="selected=null"><form class="space-y-4 p-6" @submit.prevent="save"><h2 class="font-serif text-2xl">{{ form.action==='delete'?'Delete this review?':'Update review' }}</h2><p class="text-sm text-muted">{{ form.action==='delete'?'This removes the review from display and from the coach’s rating. A recoverable record and audit entry are retained.':'Highlighting publishes the comment anonymously on this coach’s profile. Marking reviewed does not publish it.' }}</p><label class="block text-sm">Moderation reason<textarea v-model="form.reason" required minlength="5" maxlength="500" class="field mt-2 w-full" rows="3" /></label><p v-for="error in form.errors" :key="error" role="alert" class="text-error">{{ error }}</p><div class="flex justify-end gap-3"><button type="button" :disabled="form.processing" @click="selected=null">Cancel</button><button class="action" :disabled="form.processing">Confirm</button></div></form></Modal>
</AdminWorkspace></AuthenticatedLayout></template>
