<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import Modal from '@/Components/Modal.vue';
import CreditShopSettings from '@/Components/CreditShopSettings.vue';
import PageLinks from '@/Components/PageLinks.vue';
import { Head, Link, useForm, router } from '@inertiajs/vue3';
import { ref } from 'vue';
const props = defineProps({ section: String, filters: Object, settings: Object, users: Object, transactions: Object, sessions: Object, forecasts: Object, audits: Object, shop: Object, packages: Array, paymentMethods: Array });
const sections = [['users','Users & Counselors'],['pricing','Pricing & Billing'],['transactions','Credit Transactions'],['sessions','Chat Sessions'],['forecasts','Forecasts'],['audit','Audit History']];
const credits = units => (Number(units) / 3600).toLocaleString(undefined, { maximumFractionDigits: 4 });
const date = value => value ? new Date(value.includes('T') ? value : value.replace(' ', 'T') + 'Z').toLocaleString() : '—';
const search = useForm({ q: props.filters.q, section: 'users' });
const pricing = useForm({ default_rate: props.settings.default_rate, minimum_credits: props.settings.minimum_credits, disconnect_seconds: props.settings.disconnect_seconds });
const selected = ref(null); const dialog = ref(null);
const account = useForm({ role: 'user', is_approved: false, is_suspended: false, rate_per_hour: null });
const adjustment = useForm({ amount: 1, kind: 'add', reason: '', session_id: null, full_refund: false });
const forecast = useForm({ id: null, title: '', body: '', published_at: '' });
const editUser = user => { selected.value = user; Object.assign(account, { role: user.role, is_approved: user.is_approved, is_suspended: user.is_suspended, rate_per_hour: user.rate_per_hour }); account.clearErrors(); dialog.value = 'account'; };
const editCredits = user => { selected.value = user; adjustment.reset(); adjustment.clearErrors(); dialog.value = 'credits'; };
const saveAccount = () => account.patch(route('admin.user', selected.value.id), { preserveScroll: true, onSuccess: () => { dialog.value = null; } });
const saveCredits = () => adjustment.post(route('admin.credits', selected.value.id), { preserveScroll: true, onSuccess: () => { dialog.value = null; } });
const editForecast = item => { forecast.reset(); forecast.clearErrors(); if (item) { forecast.id = item.id; forecast.title = item.title; forecast.body = item.body; if (item.published_at) { const d = new Date(item.published_at.replace(' ', 'T') + 'Z'); forecast.published_at = new Date(d.getTime() - d.getTimezoneOffset()*60000).toISOString().slice(0,16); } } dialog.value = 'forecast'; };
const saveForecast = () => forecast.transform(data => ({ ...data, published_at: data.published_at ? new Date(data.published_at).toISOString() : null })).post(route('admin.forecast'), { onSuccess: () => { dialog.value = null; } });
const deletingForecast = ref(null);
const deletion = useForm({});
const confirmDeleteForecast = item => { deletingForecast.value = item; deletion.clearErrors(); dialog.value = 'delete-forecast'; };
const deleteForecast = () => deletion.delete(route('admin.forecast.delete', deletingForecast.value.id), { preserveScroll: true, onSuccess: () => { dialog.value = null; deletingForecast.value = null; } });
const ending = ref(null);
const endReading = session => { ending.value = session; dialog.value = 'end'; };
</script>
<template>
    <Head title="Admin Settings" />
    <AuthenticatedLayout>
        <main class="mx-auto max-w-7xl px-5 py-10">
            <p class="text-xs uppercase tracking-widest text-accent-text">Administration</p><h1 class="mt-2 font-serif text-4xl">Admin Settings</h1>
            <p class="mt-3 text-muted">Manage accounts, reading prices, and every credit movement.</p>
            <nav aria-label="Admin sections" class="my-7 flex flex-wrap gap-2"><Link v-for="[key,label] in sections" :key="key" :href="route('admin.settings', { section: key })" class="rounded-full px-4 py-2 text-sm" :class="section === key ? 'bg-primary text-on-primary' : 'bg-surface border border-border'">{{ label }}</Link></nav>
            <p v-if="$page.props.flash.success" role="status" class="mb-5 rounded-xl bg-accent-soft p-4 text-accent-text">{{ $page.props.flash.success }}</p>
            <p v-for="(error,key) in $page.props.errors" :key="key" role="alert" class="mb-3 text-error">{{ error }}</p>
            <section v-if="section === 'users'">
                <form @submit.prevent="search.get(route('admin.settings'))" class="mb-6 flex gap-3"><label for="account-search" class="sr-only">Search accounts</label><input id="account-search" v-model="search.q" class="field flex-1" placeholder="Search name or email" maxlength="100" /><button class="action" :disabled="search.processing">Search</button></form>
                <div class="overflow-x-auto rounded-xl border border-border bg-surface"><table class="w-full text-left text-sm"><thead class="bg-page"><tr><th>Account</th><th>Access</th><th>Credits</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="u in users.data" :key="u.id" class="border-t border-border"><td><strong>{{ u.name }}</strong><p class="text-xs text-muted">#{{ u.id }} · {{ u.email }}</p></td><td class="capitalize">{{ u.role }}</td><td>{{ credits(u.credit_units) }}</td><td>{{ u.is_suspended ? 'Suspended' : u.role === 'counselor' ? u.is_approved ? 'Approved' : 'Awaiting approval' : 'Active' }}</td><td><button class="text-accent-text underline" @click="editUser(u)">Edit access</button><button class="ml-4 text-accent-text underline" @click="editCredits(u)">Adjust credits</button></td></tr></tbody></table></div><p v-if="!users.data.length" class="mt-6 text-muted">No accounts found.</p><PageLinks :data="users" />
            </section>
            <form v-if="section === 'pricing'" @submit.prevent="pricing.patch(route('admin.pricing'))" class="max-w-xl space-y-5 rounded-2xl border border-border bg-surface p-7">
                <h2 class="font-serif text-2xl">Default reading prices</h2>
                <label class="block">Credits per hour<input v-model.number="pricing.default_rate" type="number" min="1" max="100000" required class="field mt-2 w-full" /></label>
                <label class="block">Minimum starting balance (credits)<input v-model.number="pricing.minimum_credits" type="number" min="1" max="1000000" required class="field mt-2 w-full" /></label>
                <label class="block">Disconnect timeout (seconds)<input v-model.number="pricing.disconnect_seconds" type="number" min="20" max="120" required class="field mt-2 w-full" /></label>
                <p class="text-sm leading-6 text-muted">Rounding: whole elapsed seconds, with exact fractional-credit accounting. No rounding up to a full minute or hour. Time is charged only while both participants confirm their connection; disconnect grace is not charged. A balance must also cover at least one second at the selected rate.</p>
                <p class="text-sm text-muted">Counselor overrides are set in Users & Counselors. Existing requests keep their agreed price and timeout.</p>
                <button class="action" :disabled="pricing.processing">Save pricing</button>
            </form>
            <CreditShopSettings v-if="section === 'pricing'" :shop="shop" :packages="packages" :payment-methods="paymentMethods" />
            <section v-if="section === 'transactions'"><h2 class="mb-4 font-serif text-2xl">Credit ledger</h2><div class="overflow-x-auto rounded-xl border border-border bg-surface"><table class="w-full text-left text-sm"><thead><tr><th>Date / ID</th><th>User</th><th>Type</th><th>Change</th><th>Balance after</th><th>Reason / Admin</th></tr></thead><tbody><tr v-for="t in transactions.data" :key="t.id" class="border-t border-border"><td>{{ date(t.created_at) }}<p class="text-xs text-muted">#{{ t.id }} · Reading {{ t.chat_session_id || '—' }}</p></td><td>{{ t.user_name || 'Closed account' }}</td><td>{{ t.kind.replaceAll('_',' ') }}</td><td>{{ credits(t.amount_units) }}</td><td>{{ credits(t.balance_units) }}</td><td>{{ t.reason }}<p class="text-xs text-muted">{{ t.actor_name || 'System' }}</p></td></tr></tbody></table></div><PageLinks :data="transactions" /></section>
            <section v-if="section === 'sessions'"><h2 class="mb-4 font-serif text-2xl">Reading sessions</h2><div class="overflow-x-auto rounded-xl border border-border bg-surface"><table class="w-full text-left text-sm"><thead><tr><th>Reading</th><th>Participants</th><th>Status</th><th>Rate / hour</th><th>Billed seconds</th><th>Charged credits</th><th></th></tr></thead><tbody><tr v-for="s in sessions.data" :key="s.id" class="border-t border-border"><td>#{{ s.id }}</td><td>{{ s.client?.name }}<p class="text-muted">{{ s.counselor?.name }}</p></td><td>{{ s.status }}<p class="text-xs text-muted">{{ s.end_reason }}</p></td><td>{{ s.agreed_rate ?? 'Legacy' }}</td><td>{{ s.billed_seconds }}</td><td>{{ credits(s.billed_units) }}</td><td><button v-if="['active','pending'].includes(s.status)" class="text-error underline" @click="endReading(s)">End reading</button></td></tr></tbody></table></div><PageLinks :data="sessions" /></section>
            <section v-if="section === 'forecasts'"><div class="mb-5 flex justify-between"><h2 class="font-serif text-2xl">Forecast publishing</h2><button class="action" @click="editForecast(null)">New forecast</button></div><article v-for="f in forecasts.data" :key="f.id" class="mb-4 rounded-xl border border-border bg-surface p-6"><h3 class="font-semibold">{{ f.title }}</h3><p class="mt-2 text-sm text-muted">{{ f.published_at ? 'Publication: ' + date(f.published_at) : 'Draft — not visible to users' }}</p><button class="mt-3 text-accent-text underline" @click="editForecast(f)">Edit</button><button type="button" class="ml-5 mt-3 text-error underline" :aria-label="'Delete forecast: ' + f.title" @click="confirmDeleteForecast(f)">Delete</button></article><p v-if="!forecasts.data.length" class="text-muted">No forecasts yet.</p><PageLinks :data="forecasts" /></section>
            <section v-if="section === 'audit'"><h2 class="mb-4 font-serif text-2xl">Audit history</h2><article v-for="a in audits.data" :key="a.id" class="mb-3 rounded-xl border border-border bg-surface p-5"><p class="font-semibold">{{ a.action }} · {{ a.target }}</p><p class="text-sm text-muted">{{ a.actor_name || 'System' }} · {{ date(a.created_at) }}</p><details class="mt-3 text-sm"><summary class="cursor-pointer text-accent-text">View changes</summary><pre class="mt-2 overflow-auto whitespace-pre-wrap">Before: {{ a.before }}
After: {{ a.after }}</pre></details></article><PageLinks :data="audits" /></section>
        </main>
        <Modal :show="dialog !== null" :closeable="!deletion.processing" @close="dialog = null">
            <div class="p-7 text-content"><button class="float-right text-muted" type="button" aria-label="Close dialog" :disabled="deletion.processing" @click="dialog = null">✕</button>
                <form v-if="dialog === 'account'" @submit.prevent="saveAccount" class="space-y-5"><h2 class="font-serif text-2xl">Access · {{ selected.name }}</h2><label class="block">Account type<select v-model="account.role" class="field mt-2 w-full"><option value="user">User</option><option value="counselor">Counselor</option><option value="admin">Admin</option></select></label><label v-if="account.role === 'counselor'" class="block">Hourly rate override (blank uses default)<input v-model="account.rate_per_hour" type="number" min="1" max="100000" class="field mt-2 w-full" /></label><label v-if="account.role === 'counselor'" class="block"><input type="checkbox" v-model="account.is_approved" /> Approve counselor for directory and readings</label><label class="block"><input type="checkbox" v-model="account.is_suspended" /> Suspend account</label><p v-for="e in account.errors" :key="e" role="alert" class="text-error">{{ e }}</p><button class="action" :disabled="account.processing">Save account</button></form>
                <form v-if="dialog === 'credits'" @submit.prevent="saveCredits" class="space-y-5"><h2 class="font-serif text-2xl">Credits · {{ selected.name }}</h2><label class="block">Action<select v-model="adjustment.kind" class="field mt-2 w-full"><option value="add">Add credits</option><option value="remove">Remove credits</option><option value="refund">Refund a completed reading</option></select></label><label v-if="adjustment.kind === 'refund'" class="block"><input type="checkbox" v-model="adjustment.full_refund" /> Refund the full remaining charge, including fractions</label><label v-if="adjustment.kind !== 'refund' || !adjustment.full_refund" class="block">Whole credits<input v-model.number="adjustment.amount" type="number" min="1" max="1000000" required class="field mt-2 w-full" /></label><label v-if="adjustment.kind === 'refund'" class="block">Reading ID<input v-model.number="adjustment.session_id" type="number" min="1" required class="field mt-2 w-full" /></label><label class="block">Reason<textarea v-model="adjustment.reason" minlength="5" maxlength="500" required class="field mt-2 w-full"></textarea></label><p class="text-sm text-muted">Refunds also reduce the counselor’s earned credits. This does not process a cash payment.</p><p v-for="e in adjustment.errors" :key="e" role="alert" class="text-error">{{ e }}</p><button class="action" :disabled="adjustment.processing">Record adjustment</button></form>
                <form v-if="dialog === 'forecast'" @submit.prevent="saveForecast" class="space-y-5"><h2 class="font-serif text-2xl">{{ forecast.id ? 'Edit' : 'New' }} forecast</h2><label class="block">Title<input v-model="forecast.title" required maxlength="200" class="field mt-2 w-full" /></label><label class="block">Content<textarea v-model="forecast.body" required maxlength="20000" rows="8" class="field mt-2 w-full"></textarea></label><label class="block">Publish at (your local time; blank = draft)<input v-model="forecast.published_at" type="datetime-local" class="field mt-2 w-full" /></label><p v-for="e in forecast.errors" :key="e" class="text-error">{{ e }}</p><button class="action" :disabled="forecast.processing">Save forecast</button></form>
                <form v-if="dialog === 'delete-forecast'" @submit.prevent="deleteForecast" class="space-y-5"><h2 class="font-serif text-2xl">Delete forecast?</h2><p class="text-muted">“{{ deletingForecast.title }}” will be permanently removed from forecasts. This cannot be undone.</p><p v-for="e in deletion.errors" :key="e" role="alert" class="text-error">{{ e }}</p><div class="flex flex-wrap gap-3"><button type="button" class="rounded-full border border-border px-5 py-3" :disabled="deletion.processing" @click="dialog = null">Cancel</button><button type="submit" class="rounded-full bg-danger px-5 py-3 font-semibold text-on-danger hover:bg-danger-hover disabled:opacity-50" :disabled="deletion.processing">{{ deletion.processing ? 'Deleting…' : 'Delete forecast' }}</button></div></form>
                <div v-if="dialog === 'end'"><h2 class="font-serif text-2xl">End reading #{{ ending.id }}?</h2><p class="my-5 text-muted">Confirmed elapsed time will be charged and the reading will close.</p><button class="action" @click="router.post(route('admin.end', ending.id), {}, { onSuccess: () => { dialog = null; } })">End reading</button></div>
            </div>
        </Modal>
    </AuthenticatedLayout>
</template>
<style scoped>th, td { padding: 1rem; vertical-align: top; }</style>
