<script setup>
import {computed,ref,watch} from 'vue';
import {Head,Link,usePage,useForm,router} from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminWorkspace from '@/Components/AdminWorkspace.vue';
import PageLinks from '@/Components/PageLinks.vue';
import Modal from '@/Components/Modal.vue';
const props=defineProps({bookings:Object,coaches:Array,availability:Array,busy:Array,durations:Array,balance:Number,reserved:Number});
const user=usePage().props.auth.user, admin=user.role==='admin', coach=user.role==='counselor';
const zone=ref(Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Manila');
const date=ref('');
const fmt=(value)=>{try{return new Intl.DateTimeFormat(undefined,{timeZone:zone.value,dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}catch{return 'Choose a valid time zone';}};
const day=(value)=>{try{return new Intl.DateTimeFormat('en-CA',{timeZone:zone.value,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));}catch{return '';}};
const form=useForm({coach_id:props.coaches[0]?.id??null,starts_at:'',minutes:20,timezone:zone.value,consent:false,reschedule_id:null});
const hours=useForm({starts_at:'',ends_at:'',timezone:'Asia/Manila'});
const action=useForm({consent:true});
const selected=ref(null),review=useForm({penalize:false,reason:''}),cancelled=ref(null);
const slots=computed(()=>{
 const items=[];const min=Date.now()+3600000;
 for(const a of props.availability.filter(a=>a.coach_id===Number(form.coach_id))){
  const end=Date.parse(a.ends_at),span=(Number(form.minutes)+10)*60000;
  for(let t=Date.parse(a.starts_at);t+span<=end;t+=15*60000){
   if(t<min||date.value&&day(t)!==date.value)continue;
   if(props.busy.some(b=>b.id!==form.reschedule_id && b.coach_id===Number(form.coach_id)&&Date.parse(b.starts_at)<t+span&&Date.parse(b.ends_at)>t))continue;
   items.push(new Date(t).toISOString());if(items.length>=60)return items;
  }
 }return items;
});
watch([()=>form.coach_id,()=>form.minutes,date,zone],()=>{form.starts_at='';form.consent=false;form.clearErrors();});
const book=()=>{form.timezone=zone.value;form.post(route('bookings.store'),{preserveScroll:true,onSuccess:()=>{form.reset('starts_at','consent','reschedule_id');}});};
const reschedule=b=>{form.coach_id=b.coach_id;form.minutes=b.minutes;form.reschedule_id=b.id;form.starts_at='';form.consent=false;window.scrollTo({top:0,behavior:'smooth'});};
const canJoin=b=>['booked','joining','active'].includes(b.status)&&Date.now()>=Date.parse(b.starts_at)&&Date.now()<=Date.parse(b.starts_at)+600000;
const decide=()=>review.post(route('bookings.review',selected.value.id),{preserveScroll:true,onSuccess:()=>selected.value=null});
</script>
<template>
 <Head title="Bookings" /><AuthenticatedLayout><component :is="admin?AdminWorkspace:'main'" section="bookings" :class="admin?'':'mx-auto max-w-6xl px-4 py-6'">
 <header class="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h1 v-if="!admin" class="font-serif text-3xl">{{coach?'Your appointments':'Book a reading'}}</h1><p class="mt-1 text-sm text-muted">{{coach?'Declare office hours, then manage your reserved sessions.':'Reserve a time. Billing begins only after you join and your coach accepts.'}}</p></div><label class="text-xs text-muted">Display time zone<input v-model="zone" class="field mt-1 block w-52 text-sm" aria-label="Display time zone" /></label></header>
 <div v-if="!coach&&!admin" class="mb-5 rounded-2xl border border-border bg-surface p-4">
  <p class="mb-3 text-sm"><strong>{{balance.toLocaleString()}} minutes available</strong> · {{reserved.toLocaleString()}} reserved <Link :href="route('credits')" class="ml-2 text-accent-text underline">Add minutes</Link></p>
  <form @submit.prevent="book" class="space-y-3"><h2 class="font-semibold">{{form.reschedule_id?'Reschedule appointment #'+form.reschedule_id:'Choose your time'}}</h2>
   <div class="grid gap-3 sm:grid-cols-3"><label class="text-xs">Spiritual Coach<select v-model.number="form.coach_id" :disabled="!!form.reschedule_id" class="field mt-1 w-full text-sm"><option v-for="c in coaches" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label class="text-xs">Duration<select v-model.number="form.minutes" class="field mt-1 w-full text-sm"><option v-for="m in durations" :key="m" :value="m">{{m}} minutes</option></select></label><label class="text-xs">Filter by date<input v-model="date" type="date" class="field mt-1 w-full text-sm" /></label></div>
   <div class="grid max-h-48 gap-2 overflow-y-auto sm:grid-cols-3"><button v-for="slot in slots" :key="slot" type="button" @click="form.starts_at=slot;form.consent=false" class="rounded-xl border px-3 py-2 text-left text-xs" :class="form.starts_at===slot?'border-primary bg-accent-soft':'border-border hover:bg-surface-hover'">{{fmt(slot)}}</button></div><p v-if="!slots.length" class="text-sm text-muted">No available slots. Try another date or coach.</p>
   <p class="text-xs leading-5 text-muted">Up to 90 days ahead, at least one hour in advance. A 10-minute buffer protects late starts. Reschedule or cancel free at least one hour before the start; later cancellations go to admin review. No-show deductions require review: 50% of each reserved package portion, or 100% after a previous penalized no-show on that package. Mixed packages are assessed separately.</p>
   <label class="flex items-start gap-2 text-xs leading-5"><input v-model="form.consent" type="checkbox" class="mt-1" />I agree to reserve {{form.minutes}} minutes, the cancellation/no-show rules, and whole-minute rounding for the reading. Unused reserved minutes are released when it ends. No card is charged by booking.</label>
   <p v-for="e in form.errors" :key="e" role="alert" class="text-sm text-error">{{e}}</p><div class="flex gap-3"><button class="action !py-2 text-sm" :disabled="!form.starts_at||!form.consent||form.processing">{{form.reschedule_id?'Confirm new time':'Reserve appointment'}}</button><button v-if="form.reschedule_id" type="button" class="text-sm underline" @click="form.reschedule_id=null;form.consent=false">Keep current booking</button></div>
  </form>
 </div>
 <details v-if="coach" class="mb-5 rounded-2xl border border-border bg-surface p-4"><summary class="cursor-pointer font-semibold">Manage office hours</summary><form @submit.prevent="hours.post(route('bookings.hours'),{preserveScroll:true,onSuccess:()=>hours.reset('starts_at','ends_at')})" class="mt-3 grid gap-3 sm:grid-cols-3"><label class="text-xs">Start<input v-model="hours.starts_at" type="datetime-local" required class="field mt-1 w-full text-sm" /></label><label class="text-xs">End<input v-model="hours.ends_at" type="datetime-local" required class="field mt-1 w-full text-sm" /></label><label class="text-xs">Office time zone<input v-model="hours.timezone" required class="field mt-1 w-full text-sm" /></label><p class="text-xs text-muted sm:col-span-3">These times are in your office time zone. Each booking needs its reading duration plus a 10-minute buffer. Leave days unavailable by not adding office hours.</p><p v-for="e in hours.errors" :key="e" class="text-error sm:col-span-3">{{e}}</p><button class="action !py-2 text-sm" :disabled="hours.processing">Add office hours</button></form><div v-for="a in availability" :key="a.id" class="mt-3 flex flex-wrap justify-between gap-2 border-t border-border pt-2 text-xs"><span>{{fmt(a.starts_at)}} — {{fmt(a.ends_at)}}</span><button type="button" class="text-error underline" @click="router.delete(route('bookings.hours.delete',a.id),{preserveScroll:true})">Remove unbooked window</button></div></details>
 <p v-for="e in action.errors" :key="e" role="alert" class="mb-3 text-sm text-error">{{e}}</p><p v-if="$page.props.errors.booking" class="mb-3 text-sm text-error">{{$page.props.errors.booking}}</p>
 <section class="space-y-3"><h2 class="font-serif text-xl">{{admin?'Appointments & reviews':'Your appointments'}}</h2><article v-for="b in bookings.data" :key="b.id" class="rounded-2xl border border-border bg-surface p-4"><div class="flex flex-wrap items-start justify-between gap-2"><div><h3 class="font-semibold">{{coach?b.client.name:b.coach.name}}<span v-if="admin" class="text-muted"> · {{b.client.name}}</span></h3><p class="mt-1 text-sm">{{fmt(b.starts_at)}} · {{b.minutes}} minutes</p><p class="mt-1 text-xs text-muted">#{{b.id}} · {{zone}} · <span class="capitalize">{{b.status}}</span></p></div><span v-if="b.penalty_units" class="text-xs text-error">{{b.penalty_units/3600}} min deducted</span></div><p v-if="b.review_reason" class="mt-2 text-xs text-muted">{{b.review_reason}}</p><p v-if="admin&&b.status==='review'" class="mt-2 text-xs">Client check-in: {{b.client_joined_at?fmt(b.client_joined_at):'None'}} · Coach check-in: {{b.coach_joined_at?fmt(b.coach_joined_at):'None'}}</p>
 <div class="mt-3 flex flex-wrap gap-4 text-sm"><button v-if="!admin&&canJoin(b)" class="font-semibold text-accent-text underline" :disabled="action.processing" @click="action.post(route('bookings.join',b.id))">{{coach?'Check in / open reading':'Join & request reading'}}</button><Link v-if="b.session&&!admin" :href="route('chat.room',b.session.conversation_id)" class="text-accent-text underline">Open conversation</Link><button v-if="!coach&&!admin&&b.status==='booked'&&Date.now()<=Date.parse(b.starts_at)-3600000" class="text-accent-text underline" @click="reschedule(b)">Reschedule</button><button v-if="['booked','joining'].includes(b.status)" class="text-muted underline" @click="cancelled=b">Cancel appointment</button><button v-if="admin&&b.status==='review'" class="text-accent-text underline" @click="selected=b;review.reset()">Review / release minutes</button></div></article><p v-if="!bookings.data.length" class="text-sm text-muted">No appointments yet.</p><PageLinks :data="bookings" /></section>
 <p class="mt-4 text-xs text-muted">Appointment updates appear in your notification bell. Refresh this page when it is time to join.</p>
 <Modal :show="!!cancelled" max-width="md" @close="cancelled=null"><form class="space-y-3 p-5" @submit.prevent="action.post(route('bookings.cancel',cancelled.id),{preserveScroll:true,onSuccess:()=>cancelled=null})"><h2 class="font-serif text-xl">Cancel appointment?</h2><p class="text-sm text-muted">Coach cancellations and client cancellations at least one hour before the start release all reserved minutes. Later client cancellations require admin review; no automatic deduction.</p><div class="flex justify-end gap-3"><button type="button" @click="cancelled=null">Keep booking</button><button class="action !py-2" :disabled="action.processing">Confirm cancellation</button></div></form></Modal>
 <Modal :show="!!selected" max-width="md" @close="selected=null"><form @submit.prevent="decide" class="space-y-3 p-5"><h2 class="font-serif text-xl">Review appointment</h2><label class="block text-sm">Decision<select v-model="review.penalize" class="field mt-1 w-full"><option :value="false">Waive penalty and release minutes</option><option :value="true">Approve documented client no-show penalty</option></select></label><div v-if="review.penalize" class="rounded-xl bg-accent-soft p-3 text-xs"><p v-for="(part,i) in selected?.penalty_quote || []" :key="i">{{part.label}} · {{part.percent}}% · {{part.units/3600}} minutes</p><p class="mt-2 font-semibold">Proposed deduction: {{(selected?.penalty_quote || []).reduce((sum,p)=>sum+p.units,0)/3600}} minutes</p></div><p class="text-xs text-muted">A penalty is allowed only after the grace period when the coach checked in but the client did not. No coach earnings are created by a penalty.</p><label class="block text-sm">Reason<textarea v-model="review.reason" required minlength="10" maxlength="1000" rows="3" class="field mt-1 w-full" /></label><p v-for="e in review.errors" :key="e" class="text-error">{{e}}</p><div class="flex justify-end gap-3"><button type="button" @click="selected=null">Cancel</button><button class="action !py-2" :disabled="review.processing">Confirm review</button></div></form></Modal>
 </component></AuthenticatedLayout>
</template>
